### ISSUE TITLE
JSON parse exception when getting values from window.sessionStorage

### ISSUE THREAD

**Issue by warmwaterkruik** [edsilv/utils#5]
**Problem**
The Storage.ts class considers each storage value as json data by parsing it as json. When running Storage::getItems it loops through all keys and can throw an error on a html value. This is an issue when integrating the library inside a CMS that also stores values in localStorage or sessionStorage. 

**Suggestion**
Catching the json exception so we can keep using the library with json data and other values.

```javascript
try {
  var item:StorageItem = JSON.parse(data);
} catch (error) {
  return null;
}
```

**Comment by edsilv** [comment]
@warmwaterkruik I've pushed a fix to the #es6 branch. This will be getting used in the UV relatively soon and will fix https://github.com/UniversalViewer/universalviewer/issues/448

**Comment by warmwaterkruik** [comment]
Awesome! That was quick. Thanks!
